<?php

namespace path1\GesUsersBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ManageUsersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ManageUsersRepository extends EntityRepository
{
}
